// Generated by docs/design/foundations/palette.py (F1, F2). Do not edit: change the
// script and run `python3 docs/design/foundations/palette.py`.

export const scales = {
  "stone": {
    "50": "#F4F8F3",
    "100": "#EDF0EB",
    "150": "#E4E7E2",
    "200": "#DADED8",
    "300": "#C5C8C3",
    "400": "#A9ACA7",
    "500": "#8C8F8A",
    "600": "#727671",
    "700": "#5C5F5A",
    "800": "#464944",
    "900": "#30332E",
    "950": "#1F211E",
    "1000": "#121511",
    "0": "#FDFFFD"
  },
  "plum": {
    "50": "#FFF3F9",
    "100": "#FEE8F4",
    "150": "#FFDAED",
    "200": "#FFCBE7",
    "300": "#F4AFD5",
    "400": "#DB8FBA",
    "500": "#C26D9F",
    "600": "#A65485",
    "700": "#88416C",
    "800": "#6B2F54",
    "900": "#4E1D3B",
    "950": "#370F28",
    "1000": "#26051A"
  },
  "amber": {
    "50": "#FFF5EC",
    "100": "#FFEBDB",
    "150": "#FEE0C7",
    "200": "#FED3AE",
    "300": "#FAB87D",
    "400": "#E29852",
    "500": "#C97717",
    "600": "#A96001",
    "700": "#884D02",
    "800": "#693A02",
    "900": "#4B2700",
    "950": "#331901",
    "1000": "#210F00"
  },
  "red": {
    "50": "#FEF4F3",
    "100": "#FFEAE7",
    "150": "#FEDED9",
    "200": "#FED0CA",
    "300": "#FEB0A7",
    "400": "#F7857A",
    "500": "#DE6056",
    "600": "#C1443D",
    "700": "#9F332D",
    "800": "#7E221E",
    "900": "#5D100F",
    "950": "#430304",
    "1000": "#2E0001"
  },
  "green": {
    "50": "#E4FFEA",
    "100": "#CCFED7",
    "150": "#C0F6CD",
    "200": "#B4EDC2",
    "300": "#99D9AA",
    "400": "#74BE89",
    "500": "#4BA368",
    "600": "#2E894F",
    "700": "#1E6F3D",
    "800": "#0E562C",
    "900": "#013D1B",
    "950": "#002910",
    "1000": "#001A08"
  }
} as const;

export const semantic = {
  "light": {
    "bg": "#EDF0EB",
    "surface": "#FDFFFD",
    "raised": "#FDFFFD",
    "fill": "#E4E7E2",
    "line": "#DADED8",
    "lineStrong": "#C5C8C3",
    "text": "#1F211E",
    "text2": "#5C5F5A",
    "text3": "#8C8F8A",
    "action": "#88416C",
    "actionPressed": "#6B2F54",
    "onAction": "#FDFFFD",
    "actionSoft": "#FEE8F4",
    "focus": "#A65485",
    "close": "#884D02",
    "closeSoft": "#FFEBDB",
    "closeBar": "#A96001",
    "over": "#9F332D",
    "overSoft": "#FFEAE7",
    "overBar": "#7E221E",
    "positive": "#1E6F3D",
    "positiveSoft": "#CCFED7",
    "disabledBg": "#E4E7E2",
    "disabledText": "#727671",
    "toast": "#1F211E",
    "onToast": "#F4F8F3",
    "scrim": "rgba(20,26,23,.38)"
  },
  "dark": {
    "bg": "#121511",
    "surface": "#1F211E",
    "raised": "#272A26",
    "fill": "#30332E",
    "line": "#3D3F3B",
    "lineStrong": "#464944",
    "text": "#F4F8F3",
    "text2": "#A9ACA7",
    "text3": "#727671",
    "action": "#F4AFD5",
    "actionPressed": "#FFCBE7",
    "onAction": "#26051A",
    "actionSoft": "#4E1D3B",
    "focus": "#F4AFD5",
    "close": "#FAB87D",
    "closeSoft": "#331901",
    "closeBar": "#FAB87D",
    "over": "#FEB0A7",
    "overSoft": "#430304",
    "overBar": "#DE6056",
    "positive": "#99D9AA",
    "positiveSoft": "#002910",
    "disabledBg": "#30332E",
    "disabledText": "#8C8F8A",
    "toast": "#F4F8F3",
    "onToast": "#121511",
    "scrim": "rgba(0,0,0,.55)"
  }
} as const;

export const categoryColors = {
  "teal": {
    "light": {
      "base": "#31A5A5",
      "soft": "#D0F1F1",
      "ink": "#036262"
    },
    "dark": {
      "base": "#50BFBE",
      "soft": "#0D3737",
      "ink": "#73DFDF"
    }
  },
  "sand": {
    "light": {
      "base": "#D6BB79",
      "soft": "#F3E9D0",
      "ink": "#6A5100"
    },
    "dark": {
      "base": "#A98F4E",
      "soft": "#3A2F14",
      "ink": "#E3C885"
    }
  },
  "blue": {
    "light": {
      "base": "#4081D2",
      "soft": "#DCEBFF",
      "ink": "#0053A4"
    },
    "dark": {
      "base": "#589AED",
      "soft": "#203147",
      "ink": "#A8CEFF"
    }
  },
  "ocean": {
    "light": {
      "base": "#066788",
      "soft": "#D3EFFD",
      "ink": "#055E7C"
    },
    "dark": {
      "base": "#2C7EA1",
      "soft": "#153443",
      "ink": "#87D6FC"
    }
  },
  "clay": {
    "light": {
      "base": "#A67A6B",
      "soft": "#FEE3D9",
      "ink": "#7B4532"
    },
    "dark": {
      "base": "#C09283",
      "soft": "#44281F",
      "ink": "#EEBEAE"
    }
  },
  "olive": {
    "light": {
      "base": "#9CA831",
      "soft": "#E8EDD3",
      "ink": "#545B00"
    },
    "dark": {
      "base": "#B5C24E",
      "soft": "#2F3317",
      "ink": "#C8D563"
    }
  },
  "indigo": {
    "light": {
      "base": "#5255B6",
      "soft": "#E4E8FF",
      "ink": "#4442B0"
    },
    "dark": {
      "base": "#737ADE",
      "soft": "#2B2E47",
      "ink": "#BEC6FF"
    }
  },
  "sage": {
    "light": {
      "base": "#588671",
      "soft": "#D5F1E4",
      "ink": "#1F634A"
    },
    "dark": {
      "base": "#6F9E89",
      "soft": "#18382B",
      "ink": "#A7D8C1"
    }
  },
  "violet": {
    "light": {
      "base": "#9565C7",
      "soft": "#EFE4FD",
      "ink": "#6C329F"
    },
    "dark": {
      "base": "#AE7EE2",
      "soft": "#362A43",
      "ink": "#D9BBFE"
    }
  },
  "rose": {
    "light": {
      "base": "#CC939C",
      "soft": "#FFE1E5",
      "ink": "#7E3E4C"
    },
    "dark": {
      "base": "#A56F78",
      "soft": "#44262C",
      "ink": "#F4B8C2"
    }
  }
} as const;

export type CategoryColor = keyof typeof categoryColors;
