// F5 (docs/design/foundations/icons.md): the 54 category icons, each with its Hebrew and English
// name and the words people search for. The picker searches all three; screen readers read the name.
export const ICON_INFO: { id: string; he: string; en: string; words: string }[] = [
  { id: 'supermarket', he: "סופרמרקט", en: "Groceries", words: "סופר מכולת קניות אוכל grocery" },
  { id: 'dining', he: "אוכל בחוץ", en: "Dining", words: "מסעדה מסעדות dining restaurant" },
  { id: 'coffee', he: "בית קפה", en: "Coffee", words: "קפה cafe" },
  { id: 'takeaway', he: "משלוחים", en: "Takeaway", words: "פיצה וולט משלוח delivery" },
  { id: 'car', he: "רכב", en: "Car", words: "אוטו תחבורה transport" },
  { id: 'fuel', he: "דלק", en: "Fuel", words: "תדלוק בנזין gas" },
  { id: 'bus', he: "תחבורה ציבורית", en: "Public transport", words: "אוטובוס רב קו bus" },
  { id: 'train', he: "רכבת", en: "Train", words: "רכבת קלה train" },
  { id: 'parking', he: "חניה", en: "Parking", words: "חניון פנגו parking" },
  { id: 'housing', he: "דיור", en: "Housing", words: "בית שכירות שכר דירה rent" },
  { id: 'mortgage', he: "משכנתא", en: "Mortgage", words: "בנק הלוואה loan" },
  { id: 'building', he: "ועד בית", en: "Building fees", words: "בניין ועד" },
  { id: 'tax', he: "ארנונה", en: "Council tax", words: "עירייה חשבון" },
  { id: 'electricity', he: "חשמל", en: "Electricity", words: "חשבונות חברת חשמל utilities bills" },
  { id: 'water', he: "מים", en: "Water", words: "תאגיד מים" },
  { id: 'gas', he: "גז", en: "Gas", words: "בלון גז" },
  { id: 'internet', he: "אינטרנט", en: "Internet", words: "וייפיי ראוטר wifi" },
  { id: 'phone', he: "סלולר", en: "Phone", words: "טלפון פלאפון mobile" },
  { id: 'subscriptions', he: "מנויים", en: "Subscriptions", words: "מנוי חודשי recurring" },
  { id: 'streaming', he: "טלוויזיה", en: "TV & streaming", words: "נטפליקס yes hot streaming" },
  { id: 'health', he: "בריאות", en: "Health", words: "רופא קופת חולים doctor" },
  { id: 'pharmacy', he: "פארם", en: "Pharmacy", words: "תרופות סופר פארם pills" },
  { id: 'fitness', he: "כושר", en: "Fitness", words: "חדר כושר ספורט gym" },
  { id: 'wellbeing', he: "טיפולים", en: "Wellbeing", words: "פסיכולוג טיפול therapy" },
  { id: 'insurance', he: "ביטוח", en: "Insurance", words: "ביטוח רכב ביטוח בריאות" },
  { id: 'kids', he: "ילדים", en: "Kids", words: "תינוק ילד baby" },
  { id: 'daycare', he: "גן וצהרון", en: "Daycare", words: "גן צהרון מעון בית ספר" },
  { id: 'hobbies', he: "חוגים", en: "Hobbies", words: "חוג ציור פעילות" },
  { id: 'education', he: "חינוך", en: "Education", words: "לימודים אוניברסיטה school" },
  { id: 'books', he: "ספרים", en: "Books", words: "ספר קריאה" },
  { id: 'shopping', he: "קניות", en: "Shopping", words: "חנות קניון" },
  { id: 'clothes', he: "בגדים", en: "Clothes", words: "ביגוד אופנה" },
  { id: 'shoes', he: "נעליים", en: "Shoes", words: "נעל" },
  { id: 'grooming', he: "טיפוח", en: "Grooming", words: "תספורת מספרה קוסמטיקה" },
  { id: 'entertainment', he: "בילויים", en: "Entertainment", words: "סרט קולנוע יציאה" },
  { id: 'music', he: "מוזיקה", en: "Music", words: "הופעה ספוטיפיי" },
  { id: 'games', he: "משחקים", en: "Games", words: "גיימינג פלייסטיישן" },
  { id: 'travel', he: "חופשות", en: "Travel", words: "טיסה חו\"ל נופש flight" },
  { id: 'hotel', he: "לינה", en: "Hotel", words: "מלון צימר" },
  { id: 'gifts', he: "מתנות", en: "Gifts", words: "מתנה יום הולדת" },
  { id: 'holidays', he: "חגים", en: "Holidays", words: "חג אירוע מסיבה" },
  { id: 'donations', he: "תרומות", en: "Donations", words: "צדקה תרומה" },
  { id: 'pets', he: "חיות מחמד", en: "Pets", words: "כלב חתול וטרינר pet dog cat" },
  { id: 'repairs', he: "תיקונים", en: "Repairs", words: "אינסטלטור שיפוץ" },
  { id: 'garden', he: "גינה", en: "Garden", words: "צמחים משתלה" },
  { id: 'furniture', he: "ריהוט", en: "Furniture", words: "רהיטים ספה איקאה" },
  { id: 'appliances', he: "מכשירי חשמל", en: "Appliances", words: "מכונת כביסה מקרר" },
  { id: 'tech', he: "מחשבים", en: "Tech", words: "מחשב אלקטרוניקה" },
  { id: 'work', he: "עבודה", en: "Work", words: "עסק משרד" },
  { id: 'cash', he: "מזומן", en: "Cash", words: "כסף מזומנים" },
  { id: 'card', he: "כרטיס אשראי", en: "Card fees", words: "עמלות כרטיס" },
  { id: 'savings', he: "חיסכון", en: "Savings", words: "חיסכון קופה" },
  { id: 'tag', he: "תגית", en: "Tag", words: "כללי תווית" },
  { id: 'other', he: "אחר", en: "Other", words: "שונות כללי" },
];
